### ISSUE TITLE
GET http://localhost:8080/users 404 (Not Found)

### ISSUE THREAD

**Issue by friedgreenrepos** [ludovicoloreti/EasyRash#1]
Ciao,ero curiosa di vedere l'applicazione (anche io sto facendo il progetti di Tecnologie Web) ma non capisco cosa non funzioni. quando apro localhost:8080 mi apre una pagine html senza contenuto e mi da questo errore " GET http://localhost:8080/users 404 (Not Found)   angular.js:10967 "
e questo "GET http://localhost:8080/events 404 (Not Found) angular.js:10967 ".
![image](https://cloud.githubusercontent.com/assets/12759493/20242471/75293dae-a92f-11e6-82d6-a84ffee9cf85.png)
e questo è quello che vedo dal prompt dei comandi.

**Comment by ludovicoloreti** [comment]
Ciao,
    se me lo ricordi lunedì mattina carico la versione finale!

Ludovico Loreti

**Comment by friedgreenrepos** [comment]
ok grazie mille

**Comment by ludovicoloreti** [comment]
Ho controllato, la versione è l'ultima.
Hai letto la descrizione del progetto dal sito del prof? ([desc progetto](http://vitali.web.cs.unibo.it/twiki/pub/TechWeb16/LezioniDelCorso/09_Progetto_r2.ppt)), e scaricato i suoi datasets ([pagina progetto del corso](http://vitali.web.cs.unibo.it/TechWeb16/ProgettoDelCorso))?
Gli utenti sono salvati dentro _mongoDB_, e per acceder via url ad esso devi anche verificare che l'indirizzo dentro `config/server/database.js` sia corretto per te.
Domanda ovvia, hai lanciato `npm install` vero?
Ciao!

**Comment by friedgreenrepos** [comment]
si descrizione e dataset li ho.
ho lanciato npm install, e installato mondoDB ma non capisco cosa voglia dire che l'indirizzo sia corretto per me... scusa se la domanda è stupida

**Comment by ludovicoloreti** [comment]
Scusa il larghissimo ritardo. Ora va di sicuro.
